version: '3'
services:
  localstack:
    container_name: localstack
    build: .
    volumes:
      - ./docker-entrypoint-aws.sh:/docker-entrypoint-initaws.d/docker-entrypoint-aws.sh
    ports:
      - '4566:4566'
      - '8080:8080'
    env_file:
      - .env