version: '3'
services:
  localstack:
    container_name: localstack
    build: .
    volumes:
      - ./docker-entrypoint-aws.sh:/docker-entrypoint-initaws.d/docker-entrypoint-aws.sh
    ports:
      - '4566:4566'
    env_file:
      - .env

  microservice1:
    build: ./microservice1
    working_dir: /var/www/
    volumes:
      - ./microservice1:/var/www/
    ports:
      - 8000:8000
    command: php artisan serve --host=0.0.0.0 --port=8000