version: '3'
services:
  localstack:
    container_name: localstack
    build: .
    volumes:
      - ./docker-entrypoint-aws.sh:/docker-entrypoint-initaws.d/docker-entrypoint-aws.sh
    ports:
      - '4566:4566'
    env_file:
      - .env

  microservice1:
    build: ./microservice1
    working_dir: /var/www/
    volumes:
      - ./microservice1:/var/www/
    ports:
      - 8000:8000
    command: php artisan serve --host=0.0.0.0 --port=8000

  microservice2:
    build: ./microservice2
    working_dir: /var/www/
    volumes:
      - ./microservice2:/var/www/
    ports:
      - 8001:8000
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./.data:/var/lib/mysql